### ISSUE TITLE
what else

### ISSUE THREAD

**Issue by irinazheltisheva** [FleekHQ/space-daemon#181]
https://github.com/FleekHQ/space-daemon/blob/69314f00f271ff6347576957434a8dfee9bfeeff/core/textile/buckd.go#L130-L130

**Comment by Blockchainbrett** [comment]
cc: @jsonsivar

**Comment by jsonsivar** [comment]
hey @irinazheltisheva, please refer to our curent active branch `alpha-release-dev` which will be merged into `master` later this week https://github.com/FleekHQ/space-daemon/blob/alpha-release-dev/core/textile/buckd.go.  I have cleaned up the TODOs in that file based on the recent works so this more up to date.

Outside of those there aren't any high level TODOs per se.  Note however there was a recent release and we are working on bug fixing and other improvements.  These are tracked in our internal Clubhouse boards but we will be looking into making a public facing tracker so we can share upcoming features and improvements.
